// generated by @ng-toolkit/universal
    const port = process.env.PORT || 4027;
    
    const server = require('./dist/Fridg/server');
    
    server.app.listen(port, () => {
        console.log("Listening on: http://localhost:" + port );
    });
